# Generated by Django 3.2.20 on 2023-07-19 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=120)),
                ('location', models.CharField(max_length=40)),
                ('content', models.TextField(blank=True, default='')),
                ('image', models.ImageField(default='', upload_to='images/')),
                ('trip_type', models.CharField(choices=[('adventure', 'Adventure'), ('relax', 'Relax'), ('romantic', 'Romantic'), ('cultural', 'Cultural'), ('consumption', 'Consumption'), ('nautical', 'Nautical'), ('gastronomic', 'Gastronomic'), ('religious', 'Religious'), ('other', 'Other')], default='', max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
