# Generated by Django 3.2.20 on 2023-09-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='infrastructure',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='post',
            name='local_access',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='post',
            name='local_population',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='post',
            name='local_security',
            field=models.IntegerField(default=5),
        ),
    ]
