# Generated by Django 3.2.20 on 2023-07-28 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Name:')),
                ('bio', models.TextField(blank=True, max_length=150, null=True, verbose_name='Bio (max 150 characters):')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('profile_pic', models.ImageField(default='../default_profile', upload_to='images/')),
                ('bg_pic', models.ImageField(default='../default_bg', upload_to='images/')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Birthday (YYYY-MM-DD)')),
                ('location', models.CharField(blank=True, max_length=30, verbose_name='Location')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
