# Generated by Django 3.2.20 on 2023-07-27 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Name:')),
                ('bio', models.TextField(blank=True, max_length=150, null=True, verbose_name='Bio (max 150 characters):')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('profile_pic', models.ImageField(default='../default_profile', upload_to='images/')),
                ('bg_pic', models.ImageField(default='../default_bg', upload_to='images/')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Birthday (YYYY-MM-DD)')),
                ('location', models.CharField(blank=True, max_length=30, verbose_name='Location')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
