# Generated by Django 3.2.20 on 2023-09-18 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactform',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='contactform',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='contactform',
            old_name='updated_date',
            new_name='updated_at',
        ),
    ]
